-- Rollback for 20260987_live_share_ends_with_last_recipient.sql
-- Restores revoke_live_share_recipient exactly as it was in production before the apply (generated by script on 2026-09-16T06:44:59.732Z).
-- WARNING: restoring brings back a live share that stays ACTIVE after its last recipient is revoked, so the phone
-- keeps taking and broadcasting GPS fixes to nobody (LOC-5).

CREATE OR REPLACE FUNCTION public.revoke_live_share_recipient(p_recipient_user_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_uid   text := auth.uid()::text;
  v_share text;
  v_message_id text;
begin
  if v_uid is null then return; end if;

  select id into v_share from public.live_shares
    where sharer_user_id = v_uid and status = 'ACTIVE';
  if v_share is null then return; end if;

  select message_id into v_message_id from public.live_share_recipients
    where share_id = v_share and recipient_user_id = p_recipient_user_id;
  if v_message_id is null then return; end if;

  delete from public.live_share_recipients
    where share_id = v_share and recipient_user_id = p_recipient_user_id;

  update public.messages
    set meta = coalesce(meta, '{}'::jsonb) || jsonb_build_object('status', 'ENDED')
    where id = v_message_id;
end $function$;
