-- Rollback for 20260982_moderation_tells_the_author.sql
-- Restores the three moderation functions exactly as they were in production before the apply (generated by script on 2026-09-16T04:30:34.317Z).
-- WARNING: restoring goes back to removing someone's post, comment or request without telling them (MOD-1), and comment
-- removals stop being recorded in admin_actions (MOD-3).

CREATE OR REPLACE FUNCTION public.admin_cancel_request(p_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_uid text := auth.uid()::text;
begin
  if v_uid is null or not public.is_admin(v_uid) then raise exception 'NOT_ALLOWED'; end if;

  update public.requests set status = 'CANCELLED' where id = p_id;
end
$function$;

CREATE OR REPLACE FUNCTION public.admin_delete_comment(p_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_uid text := auth.uid()::text;
begin
  if v_uid is null or not public.is_admin(v_uid) then raise exception 'NOT_ALLOWED'; end if;

  delete from public.comment_reactions where comment_id = p_id;
  -- Nested replies would otherwise be orphaned behind a removed parent.
  delete from public.post_comments where parent_id = p_id;
  delete from public.post_comments where id = p_id;
end
$function$;

CREATE OR REPLACE FUNCTION public.admin_delete_post(p_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_uid text := auth.uid()::text;
begin
  if v_uid is null or not public.is_admin(v_uid) then raise exception 'NOT_ALLOWED'; end if;

  delete from public.post_comments where post_id = p_id;
  delete from public.post_likes where post_id = p_id;
  delete from public.poll_votes where post_id = p_id;
  delete from public.community_posts where id = p_id;
end
$function$;
