-- Rollback for 20260980_notifications_insert_authorized.sql
-- Restores production's INSERT policy on public.notifications and on_queue_token_update exactly as they were before the
-- apply, and drops request_payment_nudge (generated by script on 2026-09-15T22:33:45.282Z).
-- WARNING: restoring re-opens E2E-040 (any signed-in user can notify / push any user). The app's payment nudges call
-- request_payment_nudge, so roll the app back too, or nudges will fail.

drop policy if exists insert_notifications on public.notifications;

create policy insert_notifications on public.notifications
  as permissive
  for insert
  to public
  with check ((( SELECT auth.role() AS role) = 'authenticated'::text));

drop function if exists public.request_payment_nudge(text, text);

-- on_queue_token_update: live definition before the apply
CREATE OR REPLACE FUNCTION public.on_queue_token_update()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_owner text;
begin
  if (new.status in ('CALLED', 'SERVED') and new.status is distinct from old.status)
     or (new.arrived_at is not null and old.arrived_at is null) then
    update public.queue_settings set last_activity_at = now() where business_id = new.business_id;
  end if;

  if new.status = 'LEFT' and old.status in ('CALLED', 'SERVED') then
    begin
      select b.owner_user_id into v_owner from public.businesses b where b.id = new.business_id;
      if v_owner is not null then
        insert into public.notifications (user_id, type, title, body, deep_link, metadata)
        values (v_owner, 'QUEUE_UPDATE', 'Customer left the queue',
                coalesce(new.customer_name, 'A customer') || ' left before paying.',
                '/business/' || new.business_id || '/manage/queue',
                jsonb_build_object('actorName', new.customer_name, 'statusPill', 'Left', 'tone', 'neutral'));
      end if;
    exception when others then null;
    end;
  end if;
  return new;
end $function$;
