-- Rollback for 20260989_rls_initplan_and_fk_indexes.sql
-- Restores the nine policy expressions exactly as the catalog held them before the apply (generated by script from
-- pg_policies on 2026-09-16T18:30:57.213Z) and drops the four indexes the migration added.
--
-- Note: production's select_custom_payments carries the same predicate with one extra pair of parentheses around the
-- first two OR branches — the same policy, printed differently by the planner. Restoring this form on production is
-- therefore behaviour-identical, not a change.
--
-- WARNING: restoring brings back auth.uid() evaluated once per row in each of these policies (advisor
-- auth_rls_initplan) and leaves the four foreign keys without a covering index.

alter policy read_bulk_deal_pledges on public.bulk_deal_pledges
  using (((user_id = (auth.uid())::text) OR (EXISTS ( SELECT 1
   FROM bulk_deals d
  WHERE ((d.id = bulk_deal_pledges.deal_id) AND has_business_access(d.business_id, (auth.uid())::text)))) OR is_admin((auth.uid())::text)));

alter policy read_bulk_deal_tokens on public.bulk_deal_tokens
  using (((holder_user_id = (auth.uid())::text) OR (issuer_user_id = (auth.uid())::text) OR ((business_id IS NOT NULL) AND has_business_access(business_id, (auth.uid())::text)) OR is_admin((auth.uid())::text)));

alter policy read_bulk_deals on public.bulk_deals
  using (((status = 'ACTIVE'::entity_status) OR (owner_user_id = (auth.uid())::text) OR is_admin()));

alter policy select_custom_payments on public.custom_payments
  using ((((auth.uid())::text = payer_user_id) OR ((auth.uid())::text = target_owner_user_id) OR ((target_type = 'BUSINESS'::text) AND has_business_scope(target_id, (auth.uid())::text, 'appointments'::text)) OR is_admin()));

alter policy read_group_buy_tokens on public.group_buy_tokens
  using (((holder_user_id = (auth.uid())::text) OR (issuer_user_id = (auth.uid())::text) OR is_admin()));

alter policy insert_places on public.places
  with check (((submitted_by_user_id = (auth.uid())::text) AND ((status = 'PENDING'::entity_status) OR is_admin())));

alter policy select_places on public.places
  using (((status = 'ACTIVE'::entity_status) OR (submitted_by_user_id = (auth.uid())::text) OR is_admin()));

alter policy update_places_owner on public.places
  using ((submitted_by_user_id = (auth.uid())::text))
  with check ((submitted_by_user_id = (auth.uid())::text));

alter policy upd_ratings on public.ratings
  using ((rater_user_id = (auth.uid())::text))
  with check ((rater_user_id = (auth.uid())::text));

drop index if exists public.bulk_deal_tokens_holder_idx;
drop index if exists public.bulk_deal_tokens_issuer_idx;
drop index if exists public.bulk_deals_owner_idx;
drop index if exists public.group_buy_tokens_issuer_idx;
