-- Rollback for 20260984_password_change_notice.sql
-- Restores set_entity_password and clear_entity_password exactly as they were in production before the apply
-- (generated by script on 2026-09-16T04:53:00.847Z).
-- WARNING: restoring goes back to changing or removing a console password — and its backup reset question — without
-- telling the owner anything (SEC-3).

CREATE OR REPLACE FUNCTION public.clear_entity_password(p_kind text, p_current_password text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
declare
  v_uid text := auth.uid()::text;
  v_existing text;
begin
  if v_uid is null then raise exception 'Not authenticated'; end if;
  if p_kind not in ('business', 'provider') then raise exception 'Invalid kind'; end if;

  select case p_kind when 'business' then business_password_hash else provider_password_hash end
    into v_existing
    from public.users
   where id = v_uid;

  if v_existing is null then return; end if;

  if not public._verify_entity_password(p_kind, v_uid, coalesce(p_current_password, '')) then
    raise exception 'Current password is incorrect';
  end if;

  if p_kind = 'business' then
    update public.users
       set business_password_hash = null,
           business_recovery_question_id = null,
           business_recovery_question_text = null,
           business_recovery_answer_hash = null
     where id = v_uid;
  else
    update public.users
       set provider_password_hash = null,
           provider_recovery_question_id = null,
           provider_recovery_question_text = null,
           provider_recovery_answer_hash = null
     where id = v_uid;
  end if;

  delete from public.entity_password_attempts where owner_user_id = v_uid and kind = p_kind;
  delete from public.entity_recovery_attempts where owner_user_id = v_uid and kind = p_kind;
end;
$function$;

CREATE OR REPLACE FUNCTION public.set_entity_password(p_kind text, p_new_password text, p_current_password text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
declare
  v_uid text := auth.uid()::text;
  v_existing text;
begin
  if v_uid is null then raise exception 'Not authenticated'; end if;
  if p_kind not in ('business','provider') then raise exception 'Invalid kind'; end if;
  if length(coalesce(p_new_password, '')) < 6 then
    raise exception 'Password must be at least 6 characters';
  end if;

  select case p_kind when 'business' then business_password_hash else provider_password_hash end
    into v_existing from public.users where id = v_uid;

  -- Reuses _verify_entity_password (not a second unguarded comparison) so
  -- changing a password shares the exact same rate limit as the switch gate
  -- itself — otherwise a hijacked session could brute force it here instead.
  if v_existing is not null then
    if not public._verify_entity_password(p_kind, v_uid, coalesce(p_current_password, '')) then
      raise exception 'Current password is incorrect';
    end if;
  end if;

  if p_kind = 'business' then
    update public.users set business_password_hash = crypt(p_new_password, gen_salt('bf')) where id = v_uid;
  else
    update public.users set provider_password_hash = crypt(p_new_password, gen_salt('bf')) where id = v_uid;
  end if;
  delete from public.entity_password_attempts where owner_user_id = v_uid and kind = p_kind;
end $function$;
