-- Rollback for 20260973_messages_insert_policy_block_check.sql
-- Restores the two INSERT policies on public.messages exactly as they were in production's pg_policies
-- before the apply (generated by script on 2026-09-15T19:19:15.957Z).
-- WARNING: restoring re-breaks chat sending (42501 on _user_blocks_exists) and re-opens the block bypass.

drop policy if exists insert_own_messages on public.messages;

create policy ins_messages on public.messages
  as permissive
  for insert
  to public
  with check ((((sender_id = (( SELECT auth.uid() AS uid))::text) AND (EXISTS ( SELECT 1
   FROM conversations c
  WHERE ((c.id = messages.conversation_id) AND ((c.participant_a = (( SELECT auth.uid() AS uid))::text) OR (c.participant_b = (( SELECT auth.uid() AS uid))::text)))))) OR ((( SELECT auth.role() AS role) = 'authenticated'::text) AND (sender_id = (( SELECT auth.uid() AS uid))::text) AND (EXISTS ( SELECT 1
   FROM conversations c
  WHERE ((c.id = messages.conversation_id) AND ((c.participant_a = (( SELECT auth.uid() AS uid))::text) OR (c.participant_b = (( SELECT auth.uid() AS uid))::text))))))));

create policy insert_own_messages on public.messages
  as permissive
  for insert
  to public
  with check (((auth.role() = 'authenticated'::text) AND (sender_id = (auth.uid())::text) AND (EXISTS ( SELECT 1
   FROM conversations c
  WHERE ((c.id = messages.conversation_id) AND ((c.participant_a = (auth.uid())::text) OR (c.participant_b = (auth.uid())::text)) AND (NOT _user_blocks_exists(c.participant_a, c.participant_b)))))));

-- notify_on_chat_message: live definition before the apply (still references the missing conversation_participants table)
CREATE OR REPLACE FUNCTION public.notify_on_chat_message()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_recipient text;
  v_sender_name text;
  v_sender_avatar text;
begin
  select user_id into v_recipient
  from public.conversation_participants
  where conversation_id = NEW.conversation_id
    and user_id <> NEW.sender_id
  limit 1;

  if v_recipient is null then return NEW; end if;

  if public._user_blocks_exists(NEW.sender_id, v_recipient) then return NEW; end if;

  select coalesce(name, alias, 'Someone'), avatar
    into v_sender_name, v_sender_avatar
    from public.users
   where id = NEW.sender_id;

  begin
    insert into public.notifications (
      user_id,
      type,
      title,
      body,
      deep_link,
      metadata
    ) values (
      v_recipient,
      'CHAT',
      coalesce(v_sender_name, 'New message'),
      case when NEW.image_url is not null and (NEW.body is null or NEW.body = '') then '📷 Sent a photo' else substring(NEW.body from 1 for 100) end,
      '/chat/' || NEW.conversation_id,
      jsonb_build_object(
        'conversationId', NEW.conversation_id,
        'senderId', NEW.sender_id,
        'senderName', v_sender_name,
        'avatarUrl', v_sender_avatar,
        'statusPill', 'New Message',
        'tone', 'brand',
        'actions', jsonb_build_array('REPLY_CHAT', 'OPEN_CHAT')
      )
    );
  exception when others then null; end;

  return NEW;
end;
$function$;

revoke all on function public.notify_on_chat_message() from public, anon, authenticated;
