-- Rollback for 20260983_entity_password_lockout_per_attempter.sql
-- Restores the three password functions exactly as they were in production before the apply, and puts the attempts
-- table back to its (owner_user_id, kind) primary key (generated by script on 2026-09-16T04:50:32.238Z).
-- WARNING: restoring re-opens SEC-2 (anyone signed in can attempt any shop's password, and five wrong guesses lock the
-- owner out) and SEC-4 (flat 15-minute lockout, no backoff). Per-attempter rows are collapsed: the newest attempt row
-- per (owner, kind) is kept, the rest are dropped, since the old key cannot hold more than one.

CREATE OR REPLACE FUNCTION public._verify_entity_password(p_kind text, p_owner_user_id text, p_password text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
declare
  v_hash text;
  v_attempt public.entity_password_attempts%rowtype;
  v_matches boolean;
  v_max_attempts constant integer := 5;
  v_window constant interval := interval '15 minutes';
  v_dummy_hash constant text := '$2a$10$CXSUxhkNpnbyeflgDI/sMei3m6s9krMAI2wx72jT.YBXr.Agkk6H2';
begin
  if p_owner_user_id is null or p_kind not in ('business','provider') then return false; end if;

  select * into v_attempt from public.entity_password_attempts
   where owner_user_id = p_owner_user_id and kind = p_kind for update;
  if v_attempt.locked_until is not null and v_attempt.locked_until > now() then
    return false;
  end if;

  select case p_kind when 'business' then business_password_hash else provider_password_hash end
    into v_hash from public.users where id = p_owner_user_id;

  -- Always run one bcrypt comparison, even with no password set, so response
  -- timing can't reveal whether one exists (same trick as verify_switch_pin).
  v_matches := crypt(coalesce(p_password, ''), coalesce(v_hash, v_dummy_hash)) = coalesce(v_hash, v_dummy_hash);

  if v_hash is not null and v_matches then
    delete from public.entity_password_attempts where owner_user_id = p_owner_user_id and kind = p_kind;
    return true;
  end if;

  insert into public.entity_password_attempts (owner_user_id, kind, fail_count, last_attempt_at, locked_until)
  values (p_owner_user_id, p_kind, 1, now(), null)
  on conflict (owner_user_id, kind) do update
  set fail_count = case
        when entity_password_attempts.last_attempt_at <= now() - v_window
          or entity_password_attempts.locked_until is not null
        then 1 else entity_password_attempts.fail_count + 1 end,
      last_attempt_at = now(),
      locked_until = case
        when (case
          when entity_password_attempts.last_attempt_at <= now() - v_window
            or entity_password_attempts.locked_until is not null
          then 1 else entity_password_attempts.fail_count + 1 end) >= v_max_attempts
        then now() + v_window else null end;

  return false;
end $function$;

CREATE OR REPLACE FUNCTION public.verify_business_password(p_business_id text, p_password text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
declare v_owner text;
begin
  if p_business_id is null then
    v_owner := auth.uid()::text;
  else
    select owner_user_id into v_owner from public.businesses where id = p_business_id;
  end if;
  return public._verify_entity_password('business', v_owner, p_password);
end $function$;

CREATE OR REPLACE FUNCTION public.verify_provider_password(p_provider_id text, p_password text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
declare v_owner text;
begin
  if p_provider_id is null then
    v_owner := auth.uid()::text;
  else
    select user_id into v_owner from public.providers where id = p_provider_id;
  end if;
  return public._verify_entity_password('provider', v_owner, p_password);
end $function$;

delete from public.entity_password_attempts a
 using public.entity_password_attempts b
 where a.owner_user_id = b.owner_user_id and a.kind = b.kind
   and (a.last_attempt_at, a.attempted_by) < (b.last_attempt_at, b.attempted_by);

alter table public.entity_password_attempts drop constraint if exists entity_password_attempts_pkey;
alter table public.entity_password_attempts
  add constraint entity_password_attempts_pkey primary key (owner_user_id, kind);

drop index if exists public.entity_password_attempts_window_idx;

alter table public.entity_password_attempts
  drop column if exists attempted_by,
  drop column if exists lockout_count;
